### ISSUE TITLE
PodLove Compatibility

### ISSUE THREAD

**Issue by mahemoff** [davatron5000/TimeJump#10]
Dave suggested PodLove raise an issue about compatibility [1]; I'm not PodLove, but I like the idea of both standards, I'm planning support on http://player.fm, and I hope other podcast apps also continue to do likewise.

I'm mainly just hoping to get a conversation going here. Perhaps we can identify where the standards overlap, where they diverge, ensure they are compatible where possible.
## What's the same

The main URL scheme in TimeJump does thankfully seem to be compatible with PodLove afaict. Both use "t" parameter and support Media Fragment URI format (raised in #7).
## What's different

**Parameter Format** TimeJump supports CGI-query style (?t=) as well as fragment identifier (#t=). PodLove only supports fragment identifier. I think it make sense to support both and is fairly easy to implement support for both.

**Discoverability** PodLove includes a `rel="http://podlove.org/deep-link"` link in the feed. This is important for podcatchers; e.g. I'd like to fall back to handling deep links on my own web app if a podcast feed indicates it cannot do so; and redirect to the official episode home if it _is_ supported. (Podcatchers without web presence could still link to third-party players supporting the standard, in the event the publisher doesn't support deep linking.)

**Other** PodLove is broader as it includes end times (ie you can specify a segment). PodLove also encompasses chapters and alternate feeds.
1. https://twitter.com/davatron5000/status/319815564996530176

**Comment by Kambfhase** [comment]
TimeJump and Podlove as in the [Podlove Web Player](https://github.com/podlove/podlove-web-player) are already fairly compatible. So, about your issues:

CGI queries is a Podlove issues.
Yes, discoverability would be nice, but its nothing that can be fixed with a JS lib.
For end times see issue #3 

Ps. Even though TimeJump.js and the Podlove spec are compatible, better not include TimeJump.js onto a page with the Podlove Web Player. Bad things will happen.

**Comment by mahemoff** [comment]
@Kambfhase Is it worth raising CGI as a Podlove issue in that case?

About discoverability - I agree, I'm more raising it to hopefully avoid a future collision if TimeJump expands its horizons.

**Comment by Kambfhase** [comment]
Feel free to open an issue: https://github.com/podlove/podlove-specifications

**Comment by davatron5000** [comment]
Hopefully all your issues got solved @mahemoff - Thanks for raising the concerns.
