### ISSUE TITLE
Double audio/playing when on Firefox

### ISSUE THREAD

**Issue by dcolanduno** [davatron5000/TimeJump#11]
While in the middle of playing an mp3 file, if I click any of the links to 'jump' around in the show, Firefox starts to play the audio from the indicated time stamp. However, the main audio does not stop. So, I end up with multiple versions of the same show playing all at once. I've tried this on about four different computers PC and Mac(OSX) and seems to happen across the board.

**Comment by dcolanduno** [comment]
Anyone have an idea?

**Comment by dcolanduno** [comment]
Ok, I figured it out, in Firefox and Firefox based browsers when I hit any of the time mark links it would just start another instance and start to play multiple of the audio on top of the already playing track. When I went in and added this to the Header of my site:

```
<!--[if IEMobile 7 ]> <html lang="en-US"class="no-js iem7"> <![endif]-->
<!--[if lt IE 7 ]> <html lang="en-US" class="no-js ie6 oldie"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en-US" class="no-js ie7 oldie"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en-US" class="no-js ie8 oldie"> <![endif]-->
<!--[if (gte IE 9)|(gt IEMobile 7)|!(IEMobile)|!(IE)]><!--><html lang="en-US" class="no-js"><!--<![endif]-->
```

It now works as it should. 

Don't know why, exactly, those conditions which all seem to only be for IE made Firefox happy. But, it has started to work as it should. 

You can see the working, happy, version now: 

http://www.skepticality.com/what-the-frak/

**Comment by jarrodpayne** [comment]
Could it be that you were previously using a non HTML5 doctype declaration? Perhaps you also changed something like `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">` to `<!DOCTYPE html>`. Just taking a stab at this one.

**Comment by dcolanduno** [comment]
Yes, the doctype was the issue with the double playing of the audio. 

However, oddly, now the play/pause buttons on the player do not show up on Firefox, but it all still works if you know where the button is supposed to be!

Derek
